version: "3"
services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
    image: "mysql:5.7"
    volumes:
      - "./data:/var/lib/mysql"
      - "./conf/my.cnf:/etc/my.cnf"
    ports:
      - "3306:3306"

  rabbitmq:
    image: "rabbitmq:latest"
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: "redis:latest"
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf:rw
      - ./redis-data/:/data:rw
    command:
      redis-server /etc/redis/redis.conf --appendonly yes
